apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: medanstore-xyz-tls
spec:
  secretName: medanstore-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: medanstore.xyz
  dnsNames:
    - medanstore.xyz
    - www.medanstore.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - medanstore.xyz
          - www.medanstore.xyz
